### PR TITLE
add jQuery to get search working in guides

### LINKED ISSUE #10455: Search not working in guides post 6.1
@landreev noticed that search is not working in the guides. The [6.1 version](https://guides.dataverse.org/en/6.1/) is fine but something after that broke it, possibly the upgrade to Sphinx 7 in https://github.com/IQSS/dataverse/pull/10103/commits/d32446ec1a72f23234136f322d0d955c7ef8d77b, part of this pull request:

- #10103

If you go to https://preview.guides.gdcc.io/en/develop/search.html?q=data&check_keywords=yes&area=default for example, you'll see "Please activate JavaScript to enable the search functionality" and the following errors about jQuery:

- `Uncaught TypeError: jQuery is not a function`
- `Uncaught TypeError: $ is not a function`

Here's a screenshot:

Screenshot 2024-04-01 at 9 29 01 PM

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

Sometime after 6.1, search stopped working in the guides.

**Which issue(s) this PR closes**:

- Closes #10455

**Special notes for your reviewer**:

I'm not sure why jQuery can't be found anymore. I found this solution here:

- https://github.com/readthedocs/sphinx_rtd_theme/issues/1452

**Suggestions on how to test this**:

Test the doc preview generated by this pull request. For example, here's a search for "data": https://dataverse-guide--10456.org.readthedocs.build/en/10456/search.html?q=data&check_keywords=yes&area=default

Here is a tarball from `build html`, built from this branch: [build.tar.gz](https://github.com/IQSS/dataverse/files/14837190/build.tar.gz)

And here is an epub, also build from this branch: [Dataverse.epub.tar.gz](https://github.com/IQSS/dataverse/files/14837219/Dataverse.epub.tar.gz)

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

No.

**Additional documentation**:

No.

### CODE REVIEW

**Review by landreev — APPROVED** [review]
thank you!
