### ISSUE TITLE
Search not working in guides post 6.1

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10455]
@landreev noticed that search is not working in the guides. The [6.1 version](https://guides.dataverse.org/en/6.1/) is fine but something after that broke it, possibly the upgrade to Sphinx 7 in https://github.com/IQSS/dataverse/pull/10103/commits/d32446ec1a72f23234136f322d0d955c7ef8d77b, part of this pull request:

- #10103

If you go to https://preview.guides.gdcc.io/en/develop/search.html?q=data&check_keywords=yes&area=default for example, you'll see "Please activate JavaScript to enable the search functionality" and the following errors about jQuery:

- `Uncaught TypeError: jQuery is not a function`
- `Uncaught TypeError: $ is not a function`

Here's a screenshot:

<img width="1474" alt="Screenshot 2024-04-01 at 9 29 01 PM" src="https://github.com/IQSS/dataverse/assets/21006/f1f43bbf-88b4-4b70-88d9-c1ef5d37ad5e">
